version: '3.4'
services:
  recoll:
    build: .
    ports:
      - "${HTTP_PORT}:8080"
    volumes:
      - "${PATH_TO_FOLDER_TO_BE_INDEXED}:/data/:ro"
      - "recolldata:/home/.recoll/"
volumes:
  recolldata:
  data-path:
     name: data
     external: false
